"""add_coluna_senha_usuario

Revision ID: 0403a2cd5812
Revises: f06dbfd098d6
Create Date: 2026-06-08 13:27:32.069946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0403a2cd5812'
down_revision = 'f06dbfd098d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_constraint(batch_op.f('equipamento_cod_sala_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'local', ['cod_sala'], ['cod_sala'], ondelete='SET NULL')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('equipamento_cod_sala_fkey'), 'local', ['cod_sala'], ['cod_sala'])
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
