"""Create usuarios, local, equipamento, solicitacao and historico_solicitacao models

Revision ID: 1392801f25d9
Revises: 
Create Date: 2026-06-01 19:50:45.343577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1392801f25d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.alter_column('cod_patrimonio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('historico_solicitacao', schema=None) as batch_op:
        batch_op.alter_column('data_alteracao',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('historico_solicitacao_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    with op.batch_alter_table('local', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.alter_column('cod_patrimonio',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint(batch_op.f('solicitacao_cod_patrimonio_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('solicitacao_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipamento', ['cod_patrimonio'], ['cod_patrimonio'])
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitacao_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('solicitacao_cod_patrimonio_fkey'), 'equipamento', ['cod_patrimonio'], ['cod_patrimonio'], ondelete='RESTRICT')
        batch_op.alter_column('atualizado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('cod_patrimonio',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('local', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('historico_solicitacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('historico_solicitacao_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'], ondelete='RESTRICT')
        batch_op.alter_column('data_alteracao',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('equipamento', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('cod_patrimonio',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
