"""ajuste estrutura banco arrumaIF: cria tabelas Mobilia, Componente, Defeitos e Solucao, ajusta solicitacao e historico

Revision ID: 474fb5ccdcef
Revises: 51ef82af819b
Create Date: 2026-06-04 15:39:05.471833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474fb5ccdcef'
down_revision = '51ef82af819b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_solicitacao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('historico_solicitacao_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('causa_diagnostico')
        batch_op.drop_column('solucao_diagnostico')

    with op.batch_alter_table('local', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.alter_column('cod_sala',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('id_defeito',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('descricao_defeito',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('solicitacao_usuario_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('solicitacao_cod_patrimonio_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipamento', ['cod_patrimonio'], ['cod_patrimonio'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitacao_cod_patrimonio_fkey'), 'equipamento', ['cod_patrimonio'], ['cod_patrimonio'])
        batch_op.create_foreign_key(batch_op.f('solicitacao_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'])
        batch_op.alter_column('descricao_defeito',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id_defeito',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cod_sala',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('local', schema=None) as batch_op:
        batch_op.alter_column('descricao',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('historico_solicitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solucao_diagnostico', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('causa_diagnostico', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('historico_solicitacao_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
