"""ajusta_local_descricao_nullable_e_novos_cruds

Revision ID: f06dbfd098d6
Revises: 51ef82af819b
Create Date: 2026-06-05 15:33:29.651139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06dbfd098d6'
down_revision = '51ef82af819b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_solicitacao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('historico_solicitacao_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('causa_diagnostico')
        batch_op.drop_column('solucao_diagnostico')

    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.alter_column('cod_sala',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('id_defeito',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('descricao_defeito',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('solicitacao_usuario_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('solicitacao_cod_patrimonio_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'equipamento', ['cod_patrimonio'], ['cod_patrimonio'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('solicitacao_cod_patrimonio_fkey'), 'equipamento', ['cod_patrimonio'], ['cod_patrimonio'])
        batch_op.create_foreign_key(batch_op.f('solicitacao_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'])
        batch_op.alter_column('descricao_defeito',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id_defeito',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cod_sala',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('historico_solicitacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solucao_diagnostico', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('causa_diagnostico', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('historico_solicitacao_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
