export { LoginPage, AdminLoginPage } from './LoginPage'
export { HomePage } from './HomePage'
export { InformativoPage } from './InformativoPage'
export { AberturaChamadoPage } from './AberturaChamadoPage'
export { AdminHomePage } from './AdminHomePage'
export { AdminEditChamadoPage } from './AdminEditChamadoPage'
